# Copyright (C) 2025 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: ei-classifier
binaries:
  - path: ../build-wasm/edge-impulse-standalone-classifier.wasm

config:
  permissions:
    - ocre_messaging