# @copyright Copyright © contributors to Project Ocre, 
# which has been established as Project Ocre a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0
# Ocre container image definition

version: '1'

name: webserver-complex
binaries:
  - path: build/webserver-complex.wasm

config:
  permissions:
    - networking
